#!/bin/bash
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#
INDEX_DIR='/'
JSON_DIR='/var/cache/duc'
DUC_DB=$JSON_DIR/duc.db
SIZE=10000000

# read OneFileSystem prop
ofs_prop=$(/sbin/e-smith/config getprop duc OneFileSystem)

if [ $ofs_prop == "enabled" ]; then
	ofs="-x"
else
	ofs=""
fi

# create backup list to exclude from indexing
EXCLUDE_PATHS=""
for b in $(/sbin/e-smith/db backups keys); do
    EXCLUDE_PATHS="$EXCLUDE_PATHS --exclude=backup-${b}"
done

# directory indexing
/usr/bin/duc index $ofs --check-hard-links $INDEX_DIR -d $DUC_DB --fs-exclude=sysfs,proc,devtmpfs,tmpfs ${EXCLUDE_PATHS}

# parse db into xml
/usr/bin/duc xml -s $SIZE -x -d $DUC_DB $INDEX_DIR > $JSON_DIR/tree.xml

# find current encoding, then convert in file json and strip lines
encoding=$(/usr/bin/file -b --mime-encoding $JSON_DIR/tree.xml)

if [ $encoding == "iso-8859-1" ]; then
    /usr/share/duc/xml2json.py --encoding iso-8859-1 $JSON_DIR/tree.xml > $JSON_DIR/duc.json
else
    /usr/share/duc/xml2json.py $JSON_DIR/tree.xml > $JSON_DIR/duc.json
fi
